#!/usr/bin/env python3

# CLI library import
import click

# Local imports
from djs.job_scheduler.scheduler import Scheduler

@click.group()
@click.option('--name', default = False)
def djs(name):
    if name:
        click.echo('Hello world and {}'.format(name))
    else:
        click.echo('Hello world')

@djs.command()
def job_scheduler():
    click.echo('Job Scheduler')

@djs.command()
def perturbation_engine():
    click.echo('Perturbation Engine')


if __name__ == "__main__":
    djs()